## Creating Array

In [32]:
import numpy as np
import math

**Array creation**

In [33]:
a = np.array([1,2,3])
print(a)

[1 2 3]


**number of dimension**

In [34]:
print(a.ndim)

1


**Multi-dimensional array**

In [35]:
b = np.array([[1,2,3],
             [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

**Length of each dimension**

In [36]:
b.shape

(2, 3)

**check the type**

In [37]:
a.dtype

dtype('int64')

In [38]:
c = np.array([2.2,5,1.1])
c.dtype

dtype('float64')

In [39]:
d =np.zeros((2,3))
print(d)

print()

e = np.ones((2,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]


**generate an array with random numbers**

In [40]:
np.random.rand(2,3)

array([[0.02747272, 0.85457177, 0.7924806 ],
       [0.6484359 , 0.02512495, 0.49898725]])

**create sequenbce of number**

In [45]:
f = np.arange(10,50,2)
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

**generate sequence of float**

In [46]:
np.linspace(0,2,15)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])