## Array Operations

In [2]:
import numpy as np

In [3]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

In [4]:
c = a - b
print(c)

[ 9 18 27 36]


In [6]:
d = a * b
print(d)

[ 10  40  90 160]


**convert farenheit to celcius**


In [8]:
farenheit = np.array([0,-10,-5,-15,0])

celcius = (farenheit - 31) * (5/9)
celcius

array([-17.22222222, -22.77777778, -20.        , -25.55555556,
       -17.22222222])

In [9]:
celcius > -20

array([ True, False, False, False,  True])

In [10]:
celcius % 2 ==0

array([False, False,  True, False, False])

**Elementwise manipulation**

In [12]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
print(A*B)

[[2 0]
 [0 4]]


**matrix product**

In [13]:
print(A@B)

[[5 4]
 [3 4]]


In [14]:
A.shape

(2, 2)

In [16]:
array1 = np.array([[1,2,3],[4,5,6]])
print(array1.dtype)

array2 =np.array([[7.1,8.2,9.1],[10.4, 11.2,12.3]])
print(array2.dtype)

int64
float64


In [17]:
array3 =array1 + array2
print(array3)
print(array3.dtype)

[[ 8.1 10.2 12.1]
 [14.4 16.2 18.3]]
float64


Upcasting is the automatic conversion of a smaller data type to a larger or more precise data type.

**numpy have many aggregation function**

In [18]:
print(array3.sum())
print(array3.max())
print(array3.min())
print(array3.mean())

79.3
18.3
8.1
13.216666666666667


In [19]:
b = np.arange(1,16,1).reshape(3,5)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
