## Indexing, Slicing, and Iterating

### Indexing

In [2]:
import numpy as np

In [4]:
a = np.array([1,3,5,7])
a

array([1, 3, 5, 7])

In [5]:
a[2]

np.int64(5)

In [6]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
a[1,1]

np.int64(4)

In [11]:
np.array([a[0,0],a[1,1],a[2,1]])

array([1, 4, 6])

In [12]:
print(a[[0,1,2],[0,1,1]])

[1 4 6]


### Boolearn indexing

In [14]:
print(a >5)

[[False False]
 [False False]
 [False  True]]


In [15]:
print(a[a>5])

[6]


### Slicing

In [16]:
a = np.array([0,1,2,3,4,5])
print(a[:3])

[0 1 2]


In [17]:
print(a[2:4])

[2 3]


In [18]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
a[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
a[:2,1:3]

array([[2, 3],
       [6, 7]])

In [23]:
sub_array = a[:2, 1:3]
print(sub_array[0,0])

sub_array[0,0] = 50
print(sub_array[0,0])

2
50


In [24]:
a[0,1]

np.int64(50)